sharkdp/fd

tests/test.sh

Fix test.sh on macos

---

README.md
src/main.rs
tests/test.sh

Add file type filtering as mentioned in #54.

Add file type filtering

---

.travis.yml

See https://blog.travis-ci.com/2017-09-22-macos-update

Try to re-enable macos on Travis

---

src/app.rs
src/fshelper/mod.rs
src/lscolors/mod.rs
src/main.rs
src/output.rs
src/walk.rs
tests/testenv/mod.rs
tests/tests.rs

Just a `rustfmt` pass in this PR. I'll do Travis setup separately. #99

Format the source code using `rustfmt`

---

appveyor.yml

@iology I've seen this in some other appveyor.yml files. Would this work?

Enable caching on appveyor

---

README.md

Added option using Nix package manager

Added another way of installation

---

.travis.yml

Using cargo-update to update the rustfmt on travis

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/exec/job.rs
src/exec/ticket.rs
src/internal.rs
src/lscolors/mod.rs
src/main.rs
src/walk.rs

- Fixed a few `cargo clippy` warnings
- Updated README
- Preparations for v5.0

Updates and preparations for v5.0

---

README.md

*Work in progress*
Initial work by @TitiAlone, see #73

Updated tutorial with real-world examples

---

src/main.rs

See comment by @Doxterpepper in #153

Remove superfluous path.replace

---

README.md

As of this morning 5.0.0 is in ports tree.

Add instructions on how to install under FreeBSD

---

src/main.rs

I think this PR is  just small code improvement , so I'd go ahead and open a PR, hope you don't mind. 
In main.rs, empty_pattern is used as a default value for pattern.
I think it's better remove empty_pattern and add "" for default pattern. Because it's more clear.

Refactoring main.rs : remove unused variable (empty_pattern)

---

.travis.yml
ci/before_deploy.bash

Disable this for now until we find a better solution.

Disable cargo fmt check

---

ci/before_deploy.bash

Fix bash_completion path in deb.

---

src/internal.rs
src/walk.rs

Introduce maximum output buffer size

---

README.md
doc/fd.1
src/app.rs
src/main.rs
tests/tests.rs

Implement -F/--fixed-strings/--literal

---

src/main.rs

Print error if user supplied path instead of search pattern

---

src/internal.rs
src/output.rs
src/walk.rs
tests/tests.rs

@PramodBisht Just f.y.i. - I have added a (unix-only) test for your `--type executable`.

Unit test for '--type executable'

---

src/app.rs
src/internal.rs
src/main.rs
src/walk.rs
tests/tests.rs

Implement '--ignore-file'

---

README.md

add software.opensuse.org link and `zypper in fd`

README: openSUSE package available

---

README.md
build.rs
src/app.rs
src/exec/command.rs
src/exec/job.rs
src/exec/mod.rs
src/fshelper/mod.rs
src/internal.rs
src/lscolors/mod.rs
src/main.rs
src/output.rs
src/walk.rs
tests/tests.rs

- re-organize `fzf` part into new section `Intergration with other programs`
- add `using fd with Emacs` part
See https://github.com/sharkdp/fd/issues/281 for details

Re-org fzf part. Doc on using fd with Emacs

---

tests/tests.rs

This adds the integration test for `--size` option.
This is my first pull request, I'd love to hear your opinion. :D

Add tests for SizeFilter (--size) fixes sharkdp/fd#289

---

src/walk.rs

loosen strict handling of missing --ignore-file

---

README.md
src/internal/filter/time.rs
src/walk.rs

Doc: add chinese readme link

---

src/app.rs
src/exec/job.rs
src/internal/opts.rs
src/main.rs
src/walk.rs

I'm not sure `--verbose` name is good.
Maybe `--show-error` is better?

Print errors when --show-errors is set

---

.travis.yml
ci/before_deploy.bash
ci/before_install.bash
ci/script.bash

First off, awesome tool! I use it almost everyday. 
This PR adds a statically linked binary for ARM to the CI build. (#320)

Add ARM static binary #320 (arm-unknown-linux-musleabihf)

---

src/exec/mod.rs

looks like a shorthand field can be used here :)

refactor: use shorthand fields

---

src/internal/opts.rs
src/main.rs
src/walk.rs

What it says on the tin. Feedback welcome if changes are required.

avoid cloning command, in the wake of 9d26b74

---

ci/before_deploy.bash

Hi this should fix https://github.com/sharkdp/fd/issues/416; cheers

Add copyright file for deb package

---

README.md

Add instructions for npm (#438)

---

README.md
doc/fd.1

Added detail on parallel execution job pool to man page and README.

---

Cargo.lock
tests/tests.rs

Support FILE_ATTRIBUTE_HIDDEN on Windows

---

Cargo.lock
Cargo.toml
src/app.rs
src/internal/mod.rs
src/internal/opts.rs
src/main.rs
src/walk.rs
tests/tests.rs

Glob-based search

---

src/walk.rs

Make --changed-within/before work for directories

---

src/app.rs

Add 'overrides_with' to format flags.
Resolves sharkdp/fd#488

Fix idempotent flags

---

doc/fd.1

man page updated for explaining search patterns.
This commit resolves #408

Update man page

---

LICENSE-MIT
README.md

- Add copyright notice to the MIT License.
- Add information about the license to README file.

Fix LICENSE

---

README.md

Fix homebrew formula link

---

doc/fd.1

resolves #544 
added short names for --one-file-system to man page

Add --one-file-system and aliases to man page

---

Cargo.lock
Cargo.toml

Update lscolors dependency

---

README.md

Translate into Korean
Hello, this is spearkkk from South korea.
I saw your nice command line util and I read docs to use `fd`.
While in reading, I think that this nice tool should be read in Korean too.
So, I just translate some part of README.md
I want to refer this translated docs into your repo.
Could you check this PR?
Let me know if you have any concern about this.
I will check again.

Add link for Korean

---

CHANGELOG.md
doc/fd.1
src/app.rs
src/main.rs
tests/tests.rs

This is an implementation for #561. Please have in mind that these are some of my first steps with Rust. :)

Add short form -1 for --max-results=1

---

CHANGELOG.md
doc/fd.1
src/app.rs
src/main.rs
src/options.rs
src/walk.rs
tests/tests.rs

Add new `--min-depth <depth>` and `--exact-depth <depth>` options in addition to the existing
option to limit the maximum depth.
closes #404

Add --min-depth and --exact-depth

---

CHANGELOG.md
src/main.rs

Always enable colors on Windows

---

src/main.rs
tests/tests.rs

MacOS and Windows support for --list-details/-l

---

CHANGELOG.md
doc/fd.1
src/app.rs
src/filesystem.rs
src/filetypes.rs
src/main.rs
src/walk.rs

Add new `--type socket` and `--type pipe` filters

---

README.md

Suggested in this comment:
https://github.com/sharkdp/fd/issues/283#issuecomment-627465260

Add as-tree to the README

---

CHANGELOG.md
src/main.rs

Revert: "Always enable colors on Windows"

---

README.md

This is to address https://github.com/sharkdp/fd/issues/622

Add documentation around regex syntax

---

doc/fd.1

Add `NO_COLOR` description under the ENVIRONMENT section in the man page.

Add NO_COLOR to the man page

---

.travis.yml
CHANGELOG.md
Cargo.lock
src/main.rs
tests/testenv/mod.rs
tests/tests.rs

Fail with error message if numeric arguments can not be parsed

---

CHANGELOG.md
src/walk.rs

Avoid panic when sending errors after receiver shutdown

---

README.md

Update README to have updated instructions.

---

doc/fd.1

- Changed "extention" to "extension"

fixed: typographic error in help

---

doc/fd.1
src/app.rs

Try to clarify the documentation for -x command

---

src/app.rs

Only a documentation change so I didn't update the changelog. 
Resolves #624 by adding some additional help text for the new aliases that were originally implemented with PR #645 . 
Also completes the last checkbox in #695 . Let me know if you want me to make any changes!

Issue 624 newer older help text

---

README.md

Hello
A handy link for people wanting to dig more into GNU parallel
Thanks

doc: add link to GNU parallel

---

README.md

Linked Issue: https://github.com/sharkdp/fd/issues/771
fd is a program to find entries in your 'filesytem'. It must be filesystem instead :)

A few spell-checks is required in the readme file

---

README.md

To make it more clear how to set up the symlin on debian/ubuntu.
Fixes #791

Add comment to README about making sure .local/bin is on PATH

---

doc/fd.1
src/app.rs

Improve -x/-X help text and man page description

---

README.md

Hello,
This PR is meant to address issue #692.
Let me know if any tweaks would make the example more clear. :)

Added example for searching exactly a filename

---

.github/workflows/CICD.yml

I don't know if you want 18.04 dropped from the CI?

Add 20.04 Ubuntu builds

---

src/filetypes.rs
src/main.rs
src/walk.rs

Refactor file types check to be on impl of FileTypes

---

README.md

Mention `make` as a build dependency.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
doc/screencast.sh
src/exec/mod.rs

Minor cleanups

---

CHANGELOG.md
doc/fd.1
src/app.rs
src/exit_codes.rs
src/main.rs
src/options.rs
src/walk.rs
tests/tests.rs

Closes #303
Hi, this seemed like a nice little opportunity for me to contribute. I'm rather new to Rust, so let me know if you think there's a better approach I could've taken.

Add -q/--quiet/--has-match flag

---

doc/fd.1

Explicitly list which files are used for gitignore.
Fixes #354

Add better documentation of vcs-ignore files.

---

.github/workflows/CICD.yml

(this is a result of a CI sync with bat and hyperfine)

Minor CI improvements

---

doc/fd.1
src/app.rs

Improve --type help text

---

CHANGELOG.md
doc/fd.1
src/filter/time.rs

Change time comparisons to exclusive

---

README.md

Add an example of the `-X` option using `rg`

---

src/output.rs
src/walk.rs

Quit senders more aggressively

---

CHANGELOG.md

I forgot to add it when I made the PR.
See commit 8bdbbd8e0cbe8ba010ce5c7f863e23af44386741

Add entry to changelog for no-ignore-vcs fix

---

contrib/completion/_fd

--no-ignore-parent and --strip-cwd-prefix

Add a couple of options to zsh completion

---

Cargo.lock
Cargo.toml

Issue was fixed upstream in https://github.com/dylni/normpath/issues/5

Update normpath to 0.3.2 to fix issue #931

---

.github/workflows/CICD.yml

Sync with `bat`s github actions file

Add clippy run in CI/CD

---

README.md

or only available on fedora rawhide

docs: readme: looks like the COPR repo is no longer maintained

---

CHANGELOG.md
README.md

Added installation instructions for RHEL8

---

CHANGELOG.md
src/main.rs
tests/testenv/mod.rs
tests/tests.rs

Allow working directory to be nonexistent if search path is given

---

README.md

this includes a statement that `fd` will not interlace or garble the terminal output from its multiple threads
this resolves #1090

add md5sum example to README

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/filesystem.rs
src/filetypes.rs

Implement --type executable on Windows

---

CHANGELOG.md
doc/fd.1
src/app.rs

Add a simple link to the man page to report bugs on Github.

Add a link back the Github page to address #1052

---

src/app.rs
src/main.rs
tests/tests.rs

Enable --strip-cwd-prefix by default except with -0

---

CHANGELOG.md
src/app.rs
src/dir_entry.rs
src/exec/job.rs
src/main.rs
src/output.rs
src/walk.rs
tests/tests.rs

Make --strip-cwd-prefix apply to -x/-X

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/cli.rs
tests/tests.rs

Make sure to `git add` the `Cargo.lock` changes as well.
`grep '^\s*MIN_SUPPORTED_RUST_VERSION' .github/workflows/CICD.yml`.
to the version of this release.
sure that it is available on the `PATH` (`fd --version` should show the
new version).
the README
next section).
in the `CHANGELOG.md`.
(after creating the GitHub release).
This will trigger the deployment via GitHub Actions.
REMINDER: If your `origin` is a fork, don't forget to push to e.g. `upstream`
instead.
release. Select the new tag and also use it as the release title. For the
release notes, copy the corresponding section from `CHANGELOG.md` and
possibly add additional remarks for package maintainers.
Publish the release.
appear when the CI run *for the Git tag* has finished).
One way to do this is to clone a fresh copy.
Put …

Preparations for fd 8.5

---

src/cli.rs
tests/tests.rs

Fix --threads/-j option value parsing

---

CHANGELOG.md
src/main.rs

Use file_stem instead of file_name for command for completions

---

CHANGELOG.md
doc/fd.1
src/cli.rs

And make some small tweaks to the help text and man page.
Closes: #982

Add --changed-after alias.

---

CHANGELOG.md
src/main.rs

Fix logic for when to read global ignore file

---

tests/tests.rs

Skip an executable test if running as root

---

README.md

Related to https://github.com/sharkdp/fd/issues/625
fd is now on Winget.

Add Winget installation reference

---

doc/fd.1

#1216 omitted to add the flag to the man page.

Add flag `--no-require-git` to man page

---

contrib/completion/_fd
doc/fd.1

- Include --and in man page and zsh completions.
- Include --no-require-git and --changed-after to zsh completions
Fixes: #1282

Add documentation and zsh updates

---

README.md

fixes #1040, since nothing has changed since [this comment](https://github.com/sharkdp/fd/issues/1040#issuecomment-1180826596) over a year ago.

fix(README.md): as-tree is unmaintained, fixes #1040

---

doc/fd.1
src/cli.rs
src/walk.rs
tests/tests.rs

Add docs and tests for ignoring .git

---

Cargo.lock
Cargo.toml

- https://github.com/BurntSushi/ripgrep/commit/d938e955af7a39ac0245b1ce84924f7f4a2141ac
- https://github.com/BurntSushi/ripgrep/pull/2624
- https://github.com/BurntSushi/ripgrep/pull/2642

Use a patched version of ignore for perf improvements

---

CHANGELOG.md
src/cli.rs
src/main.rs

fix: Respect NO_COLOR with --list-details option

---

Cargo.lock
Cargo.toml

Update clap version

---

src/dir_entry.rs
src/exec/token.rs
src/regex_helper.rs
src/walk.rs

Hello. Not sure if this warranted updating the changelog

Clean up clippy warnings

---

.github/workflows/CICD.yml
tests/tests.rs

Add clippy using latest rust version to CI

---

CHANGELOG.md
doc/fd.1
src/filter/time.rs

Add support for @%s time format

---

.github/workflows/CICD.yml

Attempt to add aarch64 osx build to CI

---

README.md

Note executable name in release debs

---

.github/workflows/CICD.yml
src/dir_entry.rs

Use next_back() instead of last()

---

Cargo.lock
Cargo.toml

To grab a double-free fix.
Link: https://github.com/crossbeam-rs/crossbeam/pull/1187

Update to crossbeam-channel 0.5.15
